# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'ml_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ml_service.proto\":\n\x0fLoadDataRequest\x12\x14\n\x0c\x64\x61taset_path\x18\x01 \x01(\t\x12\x11\n\tfile_data\x18\x02 \x01(\x0c\"4\n\x10LoadDataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\":\n\x11TrainModelRequest\x12\x0e\n\x06\x65pochs\x18\x01 \x01(\x05\x12\x15\n\rlearning_rate\x18\x02 \x01(\x02\"Q\n\x12TrainModelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x19\n\x11training_accuracy\x18\x03 \x01(\x02\x32s\n\tMLService\x12/\n\x08LoadData\x12\x10.LoadDataRequest\x1a\x11.LoadDataResponse\x12\x35\n\nTrainModel\x12\x12.TrainModelRequest\x1a\x13.TrainModelResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOADDATAREQUEST']._serialized_start=20
  _globals['_LOADDATAREQUEST']._serialized_end=78
  _globals['_LOADDATARESPONSE']._serialized_start=80
  _globals['_LOADDATARESPONSE']._serialized_end=132
  _globals['_TRAINMODELREQUEST']._serialized_start=134
  _globals['_TRAINMODELREQUEST']._serialized_end=192
  _globals['_TRAINMODELRESPONSE']._serialized_start=194
  _globals['_TRAINMODELRESPONSE']._serialized_end=275
  _globals['_MLSERVICE']._serialized_start=277
  _globals['_MLSERVICE']._serialized_end=392
# @@protoc_insertion_point(module_scope)
